# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cbca3e55a9c37a270edcc4723213a77dbdc58dff843619bf7ed6f76c6301788875f8cbdd8597d5aedb2c1d5bd3e0760cc852c5c369877d11f25d472713444a6

test:
  secret_key_base: e3db0c4b7917ab2825cf01ecf18384fbbde03bbdd5e159cc8c97bfd08e71526677bcfc69edf86744b4e417e9a3826837bd66162d6315627053fb90c19cc5e7e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
